apiVersion: apps/v1
kind: Deployment
metadata:
  name: yopass
spec:
  replicas: 5
  selector:
    matchLabels:
      app.kubernetes.io/name: yopass
  template:
    metadata:
      labels:
        app.kubernetes.io/name: yopass
    spec:
      containers:
        - name: yopass
          image: jhaals/yopass
          args:
            - "--redis=redis://localhost:6379"
          ports:
            - name: http
              containerPort: 1337
        - name: yopass-redis
          image: redis
          args:
            - "-m 64"
          ports:
            - name: redis
              containerPort: 6379
---
kind: Service
apiVersion: v1
metadata:
  name: yopass
spec:
  selector:
    app.kubernetes.io/name: yopass
  type: ClusterIP
  ports:
    - name: http
      port: 1337
---
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: yopass
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: yopass
  minReplicas: 2
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 80

